config/routes.rb
Rails.application.routes.draw do

  devise_for :admin,skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers,skip: [:passwords] ,controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  root to: 'homes#top'

  get '/about' => "homes#about",as: "about"


  scope module: :public do

  #root to: 'homes#top'


  get '/customers/mypage' => "customers#show"

  get '/customers/info/edit' => "customers#edit"

  #patch '/customers' => 'customers#update'

  get '/customers/confirm' => 'customers#confirm'

  patch '/customers/withdrawal' => 'customers#withdrawal'


  #get '/cart_items' => 'cart_items#index'

  #patch '/cart_items/:id' => 'cart_items#update'

  #delete '/cart_items/:id/remove' => "cart_items#destroy"

  delete '/cart_items/remove' => "cart_items#destroy_all"


  #get '/orders/new' => "orders#new"

  post '/orders/confirm' => 'orders#confirm'

  get '/orders/complete' => "orders#complete"

  #get '/orders' => "orders#index"

  #get '/orders/:id' => "orders#show"


  #get '/deliveries' => "deliveries#index"

  #get '/deliveries/:id/edit' => "deliveries#edit"

  #patch '/deliveries/:id' => "deliveries#update"

  #delete '/deliveries/:id' => "deliveries#destroy"

  resources :items, only: [:show,:index]
  resources :customers, only: [:show,:edit,:update]
  resources :cart_items, only: [:update,:index,:destroy,:create]
  resources :orders, only: [:new,:create,:index,:show]
  resources :deliveries, only: [:index,:edit,:create,:update,:destroy]

  end


  namespace :admin do
    root to: 'homes#top'
    get '/admin' => "homes#top",as: "admin"
    resources :items, only: [:new,:show,:index,:edit,:create,:update]
    resources :genres, only: [:index,:edit,:create,:update]
    resources :customers, only: [:show,:index,:edit,:update]
    resources :orders, only: [:show,:update]
    resources :order_items, only: [:update]
  end



end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end





end

app/models/admin.rb
class Admin < ApplicationRecord

  has_one_attached :image

  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item

  belongs_to :customer


end

app/models/customer.rb
class Customer < ApplicationRecord

  has_many :cart_items, dependent: :destroy

  has_many :orders, dependent: :destroy,through: :cart_items, source: :order

  has_many :addresses, dependent: :destroy


  has_one_attached :image

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   def active_for_authentication?
    super && (is_deleted == false)
   end



end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy


end

app/models/item.rb
class Item < ApplicationRecord

    belongs_to :genre

    has_many :order_items, dependent: :destroy

    has_many :cart_items, dependent: :destroy

  has_one_attached :image


end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer

  has_many :order_items, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }

  #enum status: { credit_card: 0, transfer: 1, transfer: 2, transfer: 3, transfer: 4 }

end

app/models/order_item.rb
class OrderItem < ApplicationRecord

    belongs_to :order

    belongs_to :item



end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  before_action :authenticate_admin!

  def create

    @genre = Genre.new(genre_params)

    @genre.save

    redirect_to admin_genres_path(@genre)

  end

  def index

    @genres = Genre.all
    @genre = Genre.new

  end

  def show

    @genres = Genre.all
    @genre = Genre.new

  end

  def edit

    @genre = Genre.find(params[:id])

  end

  def update

  end




  private
    def genre_params
      params.require(:genre).permit(:name)
    end





end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  before_action :authenticate_admin!

  def top

    @orders = Order.all

    @customer = current_customer

    @cart_items = CartItem.all


  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!

  def new

    @item = Item.new

  end

  def create

    @item = Item.new(item_params)

    @item.save

    redirect_to admin_item_path(@item)

  end

  def show

    @item = Item.find(params[:id])

  end

  def index

    @items = Item.all

  end

  def edit

    @item = Item.find(params[:id])


  end


  def update

    @item = Item.find(params[:id])
    @item.update(item_params)
    @item.save

    redirect_to admin_item_path(@item.id)

  end


  private
    def item_params
      params.require(:item).permit(:image,:name,:introduction,:price,:genre_id,:is_active)
    end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  before_action :authenticate_admin!

  def show

    @orders = Order.all

    @order = Order.find(params[:id])

    @customer = @order.customer

    @orderitem = @order.order_items

    @cart_items = CartItem.all


  end

  private
    def order_params
      params.require(:order).permit(:customer_id,:postal_code,:address,:name,
      :shipping_cost,:total_payment,:payment_method)
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?


   def after_sign_up_path_for(resource)

   end

   def after_sign_in_path_for(_resource)

   end

   def after_sign_out_path_for(_resource)

   end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name,:first_name,:last_name_kana,:first_name_kana,
    :postal_code,:address,:telephone_number,:is_deleted])
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  
  def top

    @items = Item.all

    #@customer = Customer.find(params[:id])


  end

  def about
  end

  def thanks
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/index.html.erb
<div class = "container">


  <div class = "row mt-3 mb-3">
　　<h5>ジャンル一覧・追加</h5>
　</div>

  <div class = "row mt-3 mb-3">

　  <!--<table class = "table table-sm table-borderless">-->

　　  <%= form_with model: @genre, url: '/admin/genres', method: :post do |f| %>

　　    <!--<tr><td>ジャンル名</td><td>-->
　　    <div class = "col-md-8">ジャンル名</div>
　　    <div class = "col-md-2"><%= f.text_field :name %></div>
　　    <div class = "col-md-2"><%= f.submit '新規登録' ,class:"btn btn-success" %></div>

　　  <% end %>

  </div>

　  <!--</table>-->

  <div class = "row mt-3 mb-3">

　　<div class = "col-md-4">

        <table class = "table">
          <thead>
            <tr>
              <th>ジャンル</th>
              <th colspan="1"></th>
            </tr>
          </thead>

          <tbody>

          <% @genres.each do |genre| %>

            <tr>
              <td><%= genre.name %></td>

              <td></td>


            </tr>

          <% end %>

          </tbody>
        </table>
    </div>

    <div class = "col-md-4"></div>
    <div class = "col-md-4"></div>

  </div>

</div>

app/views/admin/items/edit.html.erb
<div class = "container">

  <div class = "row mt-3 mb-3 justify-content-md-center">
    <h5>商品編集</h5>
  </div>

  <div class = "row mt-3 mb-3">

    <div class = "col-md-2"></div>

    <div class = "col-md-8">

    <%= form_with model: @item,url:admin_item_path(@item.id),method: :PATCH  do |f| %>

      <table class = "table table-borderless">

        <tr><td>商品画像</td><td>
        <%= f.file_field :image, accept: "image/*" %></td></tr>

        <tr><td>商品名</td><td>
        <%= f.text_field :name %></td></tr>

        <tr><td>商品説明</td><td>
        <%= f.text_area :introduction,size: "30×30" %></td></tr>

        <tr><td>ジャンル</td><td>
        <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %></td></tr>

        <tr><td>税抜価格</td><td>
        <%= f.text_field :price %>円</td></tr>

        <tr><td>販売ステータス</td><td>
        <%= f.radio_button :is_active,true %>
        <%= f.label :is_active_now_on_sale, "販売中" %>

        <%= f.radio_button :is_active,false %>
        <%= f.label :is_active_suspension_of_sales, "販売停止中" %></td></tr>

       </table>
    </div>

    <div class = "col-md-2"></div>

  </div>

  <div class = "row mt-3 mb-3">

    <div class = "col-md-5"></div>

    <div class = "col-md-6">

      <%= f.submit '変更を保存' ,class:"btn btn-success" %>

    </div>

    <div class = "col-md-2"></div>

    <% end %>

  </div>

</div>

app/views/admin/items/index.html.erb
<div class = "container">

  <div class = "row mt-3 mb-3">
    
    <div class = "col-md-9">
      <h5>商品一覧</h5>
    </div>

    <div class = "col-md-2">
      <%= link_to "新規登録",new_admin_item_path, class:"btn btn-success" %>
    </div>

      <div class = "col-md-1"></div>
  </div>

  <div class = "row mt-3 mb-3">

        <table class = "table">
          <thead>
            <tr class="table-active">
              <th >商品ID</th>
              <th>商品名</th>
              <th>価格</th>
              <th>ジャンル</th>
              <th>ステータス</th>
            </tr>
          </thead>

          <tbody>

            <% @items.each do |item| %>

            <tr>
              <td ><%= item.id %></td>

              <td><%= link_to item.name, admin_item_path(item.id)  %></td>

              <td><%= item.price %></td>

              <td><%= item.genre.name %></td>

              <% if item.is_active == true %>

              <td class="text-success"><%= "販売中" %></td>

              <% else %>

              <td class="text-secondary"><%= "販売停止中" %></td>

              <% end %>

            </tr>

            <% end %>

          </tbody>
        </table>


  </div>
</div>

app/views/admin/items/new.html.erb
<div class = "container">

  <div class = "row mt-3 mb-3 justify-content-md-center">
    <h5>商品新規登録</h5>
  </div>

  <div class = "row mt-3 mb-3 justify-content-md-center">

      <%= form_with model: @item, url: '/admin/items', method: :post do |f| %>

        <table class = "table table-borderless">

          <tr><td>商品画像</td><td>
          <%= f.file_field :image, accept: "image/*" %></td></tr>

          <tr><td>商品名</td><td>
          <%= f.text_field :name %></td></tr>

          <tr><td>商品説明</td><td>
          <%= f.text_area :introduction,size: "30×30" %></td></tr>

          <tr><td>ジャンル</td><td>
          <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %></td></tr>

          <tr><td>価格</td><td>
          <%= f.text_field :price %>円</td></tr>

          <tr><td>販売ステータス</td><td>
          <%= f.radio_button :is_active,true %>
          <%= f.label :is_active_now_on_sale, "販売中" %>

          <%= f.radio_button :is_active,false %>
          <%= f.label :is_active_suspension_of_sales, "販売停止中" %></td></tr>

        </table>

          <div class = "row mt-3 mb-3">&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;

            <%= f.submit '新規登録' ,class:"btn btn-success" %>

          </div>

      <% end %>

  </div>

</div>

app/views/admin/items/show.html.erb
<div class = "container">

  <div class = "row mt-3 mb-3 justify-content-md-center">
    <h5>商品詳細</h5>
  </div>

  <div class = "row mt-5 mb-3 justify-content-md-center">

    <div class = "col-xs-3">

    <%= image_tag @item.image, width:250,height:200 %>

    &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;

    </div>

    <div class = "col-xs-9">

        <table class = "table table-borderless">

              <tr><td>商品名</td><td><%= @item.name %></td></tr>
              <tr><td>商品説明</td><td><%= @item.introduction %></td></tr>
              <tr><td>ジャンル</td><td><%= @item.genre.name %></td></tr>
              <tr><td>価格</td><td><%= @item.price %>円</td></tr>
              <tr><td>販売ステータス</td>

                <% if @item.is_active == true %>
                <td class="text-success"><%= "販売中" %></td>
                 <% else %>

                <td class="text-secondary"><%= "販売停止中" %></td>

                <% end %>

              </tr>

        </table>

    </div>

  </div>

  <div class = "row mt-3 mb-3">

    <div class = "col-md-5"></div>

    <div class = "col-md-6">

      <%= link_to "編集する",edit_admin_item_path(@item.id), class:"btn btn-success" %>

    </div>

    <div class = "col-md-2"></div>

  </div>

</div>

app/views/admin/orders/show.html.erb
<div class = "container">

  <div class = "row mt-3 mb-3">
    <div class = "col-md-8">
      <h5>注文履歴詳細</h5>
    </div>
  </div>

      <table class = "table table-borderless">

        <tr><th>購入者</th><td><%= link_to admin_customer_path(@customer.id), class:'text-black' do %>
        <%= @order.customer.last_name %><%= @order.customer.first_name %>
        <% end %></td></tr>

        <tr><th><%= "注文日" %></th><td><%= @order.created_at.strftime('%Y/%m/%d') %></td></tr>

        <tr><th>配送先</th><td><%= "〒" %><%= @order.postal_code %>
        <%= @order.address %><br>
        <%= @order.name %></td></tr>

        <tr><th>支払方法</th><td><%= @order.payment_method_i18n %></td></tr>

      </table>


  <div class = "row mt-3 mb-3">

    <div class = "col-md-8">

        <table class = "table table-bordered">
          <thead>
            <tr>
              <th>商品名</th>
              <th>価格</th>
              <th>数量</th>
              <th>小計</th>
            </tr>
          </thead>

          <tbody>

            <% @total = 0 %>

            <% @orderitem.each do |orderitem| %>

            <tr>

              <td><%= orderitem.item.name %></td>

              <td><%= orderitem.item.price %></td>

              <td><%= orderitem.quantity %></td>

              <td><%= orderitem.item.price * orderitem.quantity %></td>

            <% @total +=  (orderitem.item.price ) * orderitem.quantity  %>

            </tr>

            <% end %>


          </tbody>
        </table>
    </div>

    <div class = "col-md-4">

        <table class = "table table-borderless">

          <div class = "col-md-4">

            <tr><th>商品合計</th><td><%= @total %></td></tr>

            <tr><th>送料</th></th><td><%= @order.shipping_cost %></td></tr>

            <tr><th>請求金額合計</th><td><%= @order.total_payment %></td></tr>

        </table>

    </div>



  </div>

</div>