config/routes.rb
Rails.application.routes.draw do

  devise_for :admin,skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers,skip: [:passwords] ,controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  root to: 'homes#top'

  get '/about' => "homes#about",as: "about"


  scope module: :public do

  #root to: 'homes#top'


  get '/customers/mypage' => "customers#show"

  get '/customers/info/edit' => "customers#edit"

  #patch '/customers' => 'customers#update'

  get '/customers/confirm' => 'customers#confirm'

  patch '/customers/withdrawal' => 'customers#withdrawal'


  #get '/cart_items' => 'cart_items#index'

  #patch '/cart_items/:id' => 'cart_items#update'

  #delete '/cart_items/:id/remove' => "cart_items#destroy"

  delete '/cart_items/remove' => "cart_items#destroy_all"


  #get '/orders/new' => "orders#new"

  post '/orders/confirm' => 'orders#confirm'

  get '/orders/complete' => "orders#complete"

  #get '/orders' => "orders#index"

  #get '/orders/:id' => "orders#show"


  #get '/deliveries' => "deliveries#index"

  #get '/deliveries/:id/edit' => "deliveries#edit"

  #patch '/deliveries/:id' => "deliveries#update"

  #delete '/deliveries/:id' => "deliveries#destroy"

  resources :items, only: [:show,:index]
  resources :customers, only: [:show,:edit,:update]
  resources :cart_items, only: [:update,:index,:destroy,:create]
  resources :orders, only: [:new,:create,:index,:show]
  resources :deliveries, only: [:index,:edit,:create,:update,:destroy]

  end


  namespace :admin do
    root to: 'homes#top'
    get '/admin' => "homes#top",as: "admin"
    resources :items, only: [:new,:show,:index,:edit,:create,:update]
    resources :genres, only: [:index,:edit,:create,:update]
    resources :customers, only: [:show,:index,:edit,:update]
    resources :orders, only: [:show,:update]
    resources :order_items, only: [:update]
  end



end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end





end

app/models/admin.rb
class Admin < ApplicationRecord

  has_one_attached :image

  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item

  belongs_to :customer


end

app/models/customer.rb
class Customer < ApplicationRecord

  has_many :cart_items, dependent: :destroy

  has_many :orders, dependent: :destroy,through: :cart_items, source: :order

  has_many :addresses, dependent: :destroy


  has_one_attached :image

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   def active_for_authentication?
    super && (is_deleted == false)
   end



end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy


end

app/models/item.rb
class Item < ApplicationRecord

    belongs_to :genre

    has_many :order_items, dependent: :destroy

    has_many :cart_items, dependent: :destroy

  has_one_attached :image


end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer

  has_many :order_items, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }

  #enum status: { credit_card: 0, transfer: 1, transfer: 2, transfer: 3, transfer: 4 }

end

app/models/order_item.rb
class OrderItem < ApplicationRecord

    belongs_to :order

    belongs_to :item



end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  before_action :authenticate_admin!

   def confirm

    @customer = current_customer

   end

  def withdrawal

    @customer = current_customer
    @customer.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path

  end

  def show

    @customer = Customer.find(params[:id])

    #@customers = current_customer

  end


  def edit

    @customer = Customer.find(params[:id])

    #@customers = current_customer


  end

  def index

    @customers = Customer.all

    @orders = Order.all


  end

  def update

    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    @customer.save

    redirect_to admin_customer_path

  end


  private
    def customer_params
      params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,
      :email,:encrypted_password,:postal_code,:address,:telephone_number)
    end




end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  before_action :authenticate_admin!

  def create

    @genre = Genre.new(genre_params)

    @genre.save

    redirect_to admin_genres_path(@genre)

  end

  def index

    @genres = Genre.all
    @genre = Genre.new

  end

  def show

    @genres = Genre.all
    @genre = Genre.new

  end

  def edit

    @genre = Genre.find(params[:id])

  end

  def update

  end




  private
    def genre_params
      params.require(:genre).permit(:name)
    end





end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  before_action :authenticate_admin!

  def top

    @orders = Order.all

    @customer = current_customer

    @cart_items = CartItem.all


  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!

  def new

    @item = Item.new

  end

  def create

    @item = Item.new(item_params)

    @item.save

    redirect_to admin_item_path(@item)

  end

  def show

    @item = Item.find(params[:id])

  end

  def index

    @items = Item.all

  end

  def edit

    @item = Item.find(params[:id])


  end


  def update

    @item = Item.find(params[:id])
    @item.update(item_params)
    @item.save

    redirect_to admin_item_path(@item.id)

  end


  private
    def item_params
      params.require(:item).permit(:image,:name,:introduction,:price,:genre_id,:is_active)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?


   def after_sign_up_path_for(resource)

   end

   def after_sign_in_path_for(_resource)

   end

   def after_sign_out_path_for(_resource)

   end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name,:first_name,:last_name_kana,:first_name_kana,
    :postal_code,:address,:telephone_number,:is_deleted])
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  
  def top

    @items = Item.all

    #@customer = Customer.find(params[:id])


  end

  def about
  end

  def thanks
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/edit.html.erb
<div class = "container">

  <div class = "row mt-3 mb-3">
    <h5><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h5>
  </div>

  <%= form_with model: @customer,url:admin_customer_path(@customer.id),method: :PATCH  do |f| %>

        <table class = "table table-borderless">

          <tr><td>会員ID</td><td><%= @customer.id %></td></tr>

          <tr><td><%= f.label :氏名 %></td><td><%= f.text_field :last_name, autocomplete: "last_name" %>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<%= f.text_field :first_name, autocomplete: "first_name" %></td></tr>

          <tr><td><%= f.label :フリガナ %></td><td><%= f.text_field :last_name_kana, autocomplete: "last_name_kana" %>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<%= f.text_field :first_name_kana, autocomplete: "first_name_kana" %></td></tr>

          <tr><td><%= f.label :郵便番号 %></td><td><%= f.text_field :postal_code, autocomplete: "postal_code" %></td></tr>

          <tr><td><%= f.label :住所 %></td><td><%= f.text_field :address, autocomplete: "address",size: "70×35" %></td></tr>

          <tr><td><%= f.label :電話番号 %></td><td><%= f.text_field :telephone_number, autocomplete: "telephone_number" %></td></tr>

          <tr><td><%= f.label :メールアドレス %></td><td><%= f.email_field :email, autofocus: true, autocomplete: "email" %></td></tr>

          <tr><td>会員ステータス</td><td>
          <%= f.radio_button :is_deleted,false %>
          <%= f.label :is_deleted_active, "有効" %>

          <%= f.radio_button :is_deleted,true %>
          <%= f.label :is_deleted_nil, "退会" %></td>

        </table>

          &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;

          <%= f.submit '変更を保存' ,class:"btn btn-success" %>

  <% end %>

</div>

app/views/admin/customers/index.html.erb
<div class = "container">

  <div class = "row mt-3 mb-3">
    <div class = "col-md-8">
      <h5>会員一覧</h5>
    </div>
  </div>

  <div class = "row mt-3 mb-3">

        <table class = "table">
          <thead>
            <tr class="table-active">
              <th>会員ID</th>
              <th>氏名</th>
              <th>メールアドレス</th>
              <th>ステータス</th>
            </tr>
          </thead>

          <tbody>

            <% @customers.each do |customer| %>

            <tr>

              <td><%= customer.id %>
              </td>

              <td><%= link_to admin_customer_path(customer.id), class:'text-black' do %>
              <%= customer.last_name %><%= customer.first_name %>
              <% end %>
              </td>

              <td><%= customer.email %>
              </td>

              <% if customer.is_deleted == true %>

              <td class="text-secondary"><%= "退会" %></td>

              <% else %>

              <td class="text-success"><%= "有効" %></td>

             <% end %>

            </tr>

            <% end %>


          </tbody>
        </table>

  </div>

</div>

app/views/admin/customers/show.html.erb
<div class = "container">

  <div class = "row mt-3 mb-3">
    <h5><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h5>
  </div>

        <table class = "table table-borderless">

          <tr><td>会員ID</td><td><%= @customer.id %></td></tr>

          <tr><td>氏名</td><td><%= @customer.last_name %>&emsp;<%= @customer.first_name %></td></tr>

          <tr><td>フリガナ</td><td><%= @customer.last_name_kana %>&emsp;<%= @customer.first_name_kana %></td></tr>

          <tr><td>郵便番号</td><td><%= @customer.postal_code %></td></tr>

          <tr><td>住所</td><td><%= @customer.address %></td></tr>

          <tr><td>電話番号</td><td><%= @customer.telephone_number %></td></tr>

          <tr><td>メールアドレス</td><td><%= @customer.email %></td></tr>

          <tr><td>会員ステータス</td>

          <% if @customer.is_deleted == true %>

              <td class="text-secondary"><%= "退会" %></td>

              <% else %>

              <td class="text-success"><%= "有効" %></td>

          <% end %>

        </table>

        <div class = "row mt-3 mb-3">

          <div class = "col-md-3">

          </div>

          <div class = "col-md-3">
            <%= link_to "編集する",edit_admin_customer_path(@customer.id), class:"btn btn-success btn-sm" %>
          </div>

          <div class = "col-md-3">
            <%= link_to "注文履歴一覧を見る",admin_root_path,class:"btn btn-primary btn-sm" %>
          </div>
        </div>

</div>