config/routes.rb
Rails.application.routes.draw do

  devise_for :admin,skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers,skip: [:passwords] ,controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  root to: 'homes#top'

  get '/about' => "homes#about",as: "about"


  scope module: :public do

  #root to: 'homes#top'


  get '/customers/mypage' => "customers#show"

  get '/customers/info/edit' => "customers#edit"

  #patch '/customers' => 'customers#update'

  get '/customers/confirm' => 'customers#confirm'

  patch '/customers/withdrawal' => 'customers#withdrawal'


  #get '/cart_items' => 'cart_items#index'

  #patch '/cart_items/:id' => 'cart_items#update'

  #delete '/cart_items/:id/remove' => "cart_items#destroy"

  delete '/cart_items/remove' => "cart_items#destroy_all"


  #get '/orders/new' => "orders#new"

  post '/orders/confirm' => 'orders#confirm'

  get '/orders/complete' => "orders#complete"

  #get '/orders' => "orders#index"

  #get '/orders/:id' => "orders#show"


  #get '/deliveries' => "deliveries#index"

  #get '/deliveries/:id/edit' => "deliveries#edit"

  #patch '/deliveries/:id' => "deliveries#update"

  #delete '/deliveries/:id' => "deliveries#destroy"

  resources :items, only: [:show,:index]
  resources :customers, only: [:show,:edit,:update]
  resources :cart_items, only: [:update,:index,:destroy,:create]
  resources :orders, only: [:new,:create,:index,:show]
  resources :deliveries, only: [:index,:edit,:create,:update,:destroy]

  end


  namespace :admin do
    root to: 'homes#top'
    get '/admin' => "homes#top",as: "admin"
    resources :items, only: [:new,:show,:index,:edit,:create,:update]
    resources :genres, only: [:index,:edit,:create,:update]
    resources :customers, only: [:show,:index,:edit,:update]
    resources :orders, only: [:show,:update]
    resources :order_items, only: [:update]
  end



end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end





end

app/models/admin.rb
class Admin < ApplicationRecord

  has_one_attached :image

  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item

  belongs_to :customer


end

app/models/customer.rb
class Customer < ApplicationRecord

  has_many :cart_items, dependent: :destroy

  has_many :orders, dependent: :destroy,through: :cart_items, source: :order

  has_many :addresses, dependent: :destroy


  has_one_attached :image

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   def active_for_authentication?
    super && (is_deleted == false)
   end



end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy


end

app/models/item.rb
class Item < ApplicationRecord

    belongs_to :genre

    has_many :order_items, dependent: :destroy

    has_many :cart_items, dependent: :destroy

  has_one_attached :image


end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer

  has_many :order_items, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }

  #enum status: { credit_card: 0, transfer: 1, transfer: 2, transfer: 3, transfer: 4 }

end

app/models/order_item.rb
class OrderItem < ApplicationRecord

    belongs_to :order

    belongs_to :item



end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  before_action :authenticate_admin!

  def create

    @genre = Genre.new(genre_params)

    @genre.save

    redirect_to admin_genres_path(@genre)

  end

  def index

    @genres = Genre.all
    @genre = Genre.new

  end

  def show

    @genres = Genre.all
    @genre = Genre.new

  end

  def edit

    @genre = Genre.find(params[:id])

  end

  def update

  end




  private
    def genre_params
      params.require(:genre).permit(:name)
    end





end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  before_action :authenticate_admin!

  def top

    @orders = Order.all

    @customer = current_customer

    @cart_items = CartItem.all


  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!

  def new

    @item = Item.new

  end

  def create

    @item = Item.new(item_params)

    @item.save

    redirect_to admin_item_path(@item)

  end

  def show

    @item = Item.find(params[:id])

  end

  def index

    @items = Item.all

  end

  def edit

    @item = Item.find(params[:id])


  end


  def update

    @item = Item.find(params[:id])
    @item.update(item_params)
    @item.save

    redirect_to admin_item_path(@item.id)

  end


  private
    def item_params
      params.require(:item).permit(:image,:name,:introduction,:price,:genre_id,:is_active)
    end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  before_action :authenticate_admin!

  def show

    @orders = Order.all

    @order = Order.find(params[:id])

    @customer = @order.customer

    @orderitem = @order.order_items

    @cart_items = CartItem.all


  end

  private
    def order_params
      params.require(:order).permit(:customer_id,:postal_code,:address,:name,
      :shipping_cost,:total_payment,:payment_method)
    end


end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?


   def after_sign_up_path_for(resource)

   end

   def after_sign_in_path_for(_resource)

   end

   def after_sign_out_path_for(_resource)

   end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name,:first_name,:last_name_kana,:first_name_kana,
    :postal_code,:address,:telephone_number,:is_deleted])
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  
  def top

    @items = Item.all

    #@customer = Customer.find(params[:id])


  end

  def about
  end

  def thanks
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/homes/top.html.erb
<div class = "container">

  <div class = "row mt-3 mb-3">
    <div class = "col-md-8">
      <h5>注文履歴一覧</h5>
    </div>
  </div>

  <div class = "row mt-3 mb-3">

        <table class = "table table-bordered">
          <thead>
            <tr>
              <th>購入日時</th>
              <th>購入者</th>
              <th>注文個数</th>
            </tr>
          </thead>

          <tbody>

            <% @orders.each do |order| %>

            <tr>

              <td><%= link_to admin_order_path(order.id), class:'text-black' do %>
                  <%= order.created_at.strftime('%Y/%m/%d') %>
                  <% end %>
              </td>

              <td><%= order.customer.last_name %><%= order.customer.first_name %>
              </td>

                  <% @total = 0 %>
              <td><% order.order_items.each do |orderitem| %>
                  <% @total += orderitem.quantity %>
                  <% end %>
                  <%= @total %>
              </td>

            </tr>

            <% end %>


          </tbody>
        </table>

  </div>

</div>

app/views/homes/about.html.erb
<center>
  <h1>About</h1>
  <br>
   <p>ながのCAKEは全国発送可能なケーキ屋さんです。</p>
   <p>お子様からお年寄りの方までお召し上がりいただけるよう、</p>
   <p>様々なバリエーションをご用意しております。</p>
   <p>また、全国へ発送可能ですので「いつ」でも「どこ」でもご注文いただけます。</p>
   <p>ぜひご注文ください。</p>
   <%= image_tag('naganocake.jpg',size: "200×200") %>
</center>

app/views/homes/thanks.html.erb
<center>

<br>
<br>
<br>
<br>
<br>
<br>

<h2>ご注文ありがとうございました！<h2>
  
  
</center>

app/views/homes/top.html.erb
<center><br>

    <div>ようこそ、ながのCAKEへ！</div>
　  <p>このサイトは、ケーキ販売のECサイトになります。</p>
    <p>会員ではない方も商品の閲覧はできますが、</p>
    <p>購入には会員登録が必要になります。</p>
    
</center>
    
<div class = "container">

  <div class = "row mt-3 mb-3">
    <div class = "col">
      <h4>新着商品</h4>
    </div>
  </div>


    <div class = "row mt-3 mb-3">

      <% @items.each do |item| %>

        <div class = "col-md-3">

          <table class = "table table-borderless">
            <thead>
              <tr>
                <th colspan="1"></th>
              </tr>
            </thead>

            <tbody>

              <tr>

                <td><%= image_tag item.image, width:150,height:150 %><br>
                <%= link_to item.name,item_path(item.id) %><br>
                <%= "￥" %><%= item.price %></td>

              </tr>

             </tbody>
          </table>

        </div>

      <% end %>

    </div>

</div>